#include "urb.h"
// generated by urbuilder
// usually at build/urb.c
#include "urb.c"

// this is slow af
char* slow_file_read(char *filename)
{
    FILE *file = fopen(filename, "r");
    if (file == NULL)
    {
        return NULL;
    }

    char *code = (char*)malloc(1);
    if (code == NULL)
    {
        printf("ERROR: could not allocate memory for file\n");
        fclose(file);
        return NULL;
    }

    code[0] = '\0';

    char *line = NULL;
    size_t len = 0;
    while (getline(&line, &len, file) != -1)
    {
        size_t new_size = strlen(code) + strlen(line) + 1;
        char *temp = realloc(code, new_size);
        if (temp == NULL)
        {
            printf("ERROR: could not reallocate memory while reading file\n");
            free(code);
            free(line);
            fclose(file);
            return NULL;
        }
        code = temp;
        strcat(code, line);
    }

    free(line);
    fclose(file);
    return code;
}

int main(int argc, char* argv[])
{
    // we expect everything to have .urb ext
    char *output_name = NULL;
    output_name = malloc(strlen(argv[1]) + 3);
    strcat(output_name, argv[1]);
    strcat(output_name, "in");

    char* file_content = slow_file_read(argv[1]);
    List* compiled = urb_preprocess(file_content);
    char* binary = malloc(sizeof(Int) * (compiled->size + 1));
    
    // we copy the metadata(.size and .capacity)
    memcpy(binary, compiled, sizeof(Int));
    
    // we copy the content(.data)
    memcpy(binary + sizeof(Int), compiled->data, compiled->size * sizeof(Int));

    FILE *file = fopen(output_name, "wb");
    if (file == NULL)
    {
        return 1;
    }
    
    fwrite(binary, 1, sizeof(Int) * (compiled->size + 1), file);
    fclose(file);

    free(output_name);
};